namespace Hecateon.Modules.Nyphos.Models;

using Hecateon.Core.Models;

/// <summary>
/// Sleep quality event for Nyphos module.
/// Tracks sleep duration, quality, and integrity.
/// </summary>
public record SleepLoggedEvent : Event
{
    public DateTime SleepStart { get; init; }
    public DateTime SleepEnd { get; init; }
    public int? QualityScore { get; init; } // 1-10
    public string[]? Interruptions { get; init; } // waking, nightmares, etc.
}

/// <summary>
/// Mood snapshot event for Nyphos module.
/// </summary>
public record MoodLoggedEvent : Event
{
    public int? EnergyLevel { get; init; } // -5 to +5 (depressed to manic)
    public int? MoodScore { get; init; } // 1-10
    public string? MoodLabel { get; init; } // stable, elevated, irritable, depressed, etc.
    public string? Notes { get; init; }
}

/// <summary>
/// Risk assessment snapshot for Nyphos module.
/// Generated by the risk engine based on recent events.
/// </summary>
public record RiskAssessmentEvent : Event
{
    public string RiskLevel { get; init; } = "Green"; // Green, Yellow, Orange, Red
    public int? SleepIntegrity { get; init; } // 0-100%
    public int? MoodRisk { get; init; } // 0-100
    public int? OverloadIndex { get; init; } // 0-100
    public string[] TopFactors { get; init; } = []; // ["poor_sleep", "elevated_mood", ...]
    public string[] RecommendedActions { get; init; } = []; // ["sleep_check", "downshift_protocol", ...]
}

/// <summary>
/// Nyphos state snapshot (derived from events).
/// </summary>
public record NyphosState
{
    public string State { get; init; } = "Green"; // Green, Yellow, Orange, Red
    public int SleepIntegrity { get; init; } = 100;
    public int MoodRisk { get; init; } = 0;
    public int OverloadIndex { get; init; } = 0;
    public string[] TopFactors { get; init; } = [];
    public string[] RecommendedActions { get; init; } = [];
    public DateTime LastUpdateUtc { get; init; } = DateTime.UtcNow;
}
